### ISSUE TITLE
nvim crashes

### ISSUE THREAD

**Issue by niekdomi** [max397574/better-escape.nvim#101] opened 2024-09-25 18:56 UTC
If I navigate through lazygit with `j` and `k`, the application crashes. Is there an option to disable the plugin inside lazygit?

**Comment by max397574** [comment] 2024-09-25 19:35
duplicate of https://github.com/max397574/better-escape.nvim/issues/81 and https://github.com/max397574/better-escape.nvim/issues/90

**Closed as not planned by max397574** 2024-09-25 19:35 UTC
