### ISSUE TITLE
Modified flag when escape without changes in insert

### ISSUE THREAD

**Issue by becarepsol** [max397574/better-escape.nvim#5] opened 2021-09-25 09:03 UTC
When I enter `insert` mode and I leave without making any changes, the buffer
is mark as modified and stacks my undo history

I don't know if this is spected behaviour, but on the ocassions when I
accidentaly enter `insert` mode without making changes it can be a little
annoying

This is my current config

```lua
use({
    "max397574/better-escape.nvim",
    event = "InsertEnter",
    after = "nvim-compe",
    config = function()
        require("better_escape").setup({
            mapping = { "jk" },
            timeout = 200,
            keys = "<esc>l",
        })
    end,
})
```

**Comment by max397574** [comment] 2021-09-25 18:31
So you type jk in insert and then those characters get deleted. That's the way this plugin works and it's like the use of it. That you really insert the characters and because of that get no delay. After that they get deleted again. That's why the buffer gets marked as modified.
So this is kinda expected behaviour.
But I'll look if there is a way to prevent it.

**Comment by max397574** [comment] 2021-10-01 05:10
It's nvim behaviour. It's the same when you enter insert mode, remove a character and at it again. As far as I have seen there is no way to change the modified state of a buffer.  The whole point of this plugin (why it has no dalay) is that the text get actually written and deleted afterwards.So this can't be fixed.

**Closed** 2021-10-04 04:43 UTC
Labels: wontfix
